listen:
  host: "0.0.0.0"
  port: 443

https:
  enable: true
  cert: "tls.crt"
  key: "tls.key"

upstreams:
  docker.xxx.com: "https://registry-1.docker.io"
  quay.xxx.com: "https://quay.io"

log_level: "INFO"